/**
 * Client-side generators for deployment artifacts: a PSAppDeployToolkit v4
 * Invoke-AppDeployToolkit.ps1 wrapper, and the matching Intune Win32-app settings (install/uninstall
 * command + detection rule). Pure string templating - nothing runs, nothing uploads.
 *
 * v4 API (verified against the official template): Open-ADTSession with an $adtSession hashtable,
 * Install/Uninstall/Repair-ADTDeployment functions, Start-ADTMsiProcess -Action for MSI and
 * Start-ADTProcess -FilePath -ArgumentList for EXEs; paths resolve against $adtSession.DirFiles.
 */
export interface PsadtInput {
  vendor: string;
  name: string;
  version: string;
  engine: string;
  fileName: string;
  installArgs: string;       // arguments after the program token (EXE engines)
  msiProductCode?: string;   // for MSI uninstall by ProductCode
  uninstallFile?: string;    // EXE uninstaller path, if known
  uninstallArgs?: string;
}

const ps = (s: string): string => s.replace(/'/g, "''"); // single-quote escape for PowerShell

/** Build the Install / Uninstall body line(s) for the detected engine. */
function actionLines(i: PsadtInput, action: 'Install' | 'Uninstall'): string {
  if (i.engine === 'msi') {
    if (action === 'Install') return `    Start-ADTMsiProcess -Action Install -FilePath '${ps(i.fileName)}'${i.installArgs ? ` -ArgumentList '${ps(i.installArgs)}'` : ''}`;
    return i.msiProductCode
      ? `    Start-ADTMsiProcess -Action Uninstall -ProductCode '${ps(i.msiProductCode)}'`
      : `    Start-ADTMsiProcess -Action Uninstall -FilePath '${ps(i.fileName)}'`;
  }
  if (action === 'Install') {
    return `    Start-ADTProcess -FilePath '${ps(i.fileName)}'${i.installArgs ? ` -ArgumentList '${ps(i.installArgs)}'` : ''}`;
  }
  if (i.uninstallFile) {
    return `    Start-ADTProcess -FilePath '${ps(i.uninstallFile)}'${i.uninstallArgs ? ` -ArgumentList '${ps(i.uninstallArgs)}'` : ''}`;
  }
  return "    # No uninstall command was auto-detected - add the vendor's uninstall switch here.";
}

export function generatePsadt(i: PsadtInput): string {
  const nm = i.name || i.fileName;
  const date = '2026-01-01'; // static; Date.now() is unavailable in this build context
  // Mirrors the official PSAppDeployToolkit v4 Invoke-AppDeployToolkit.ps1 template (scriptblock phases
  // + Open-ADTSession bootstrap). The module is imported with a 4.0.0 FLOOR (a module-spec ModuleVersion
  // is a minimum), so any v4 the user has - bundled 4.1.x/4.2.x template or PSGallery install - loads;
  // pinning an exact version fails when the user's template bundles an older v4. The
  // Remove-ADTHashtableNullOrEmptyValues step strips empty values (AppVendor/AppVersion/
  // DeployAppScriptParameters) so Open-ADTSession won't reject them.
  return `<#
.SYNOPSIS
    PSAppDeployToolkit v4 deployment script for ${nm}.
    Generated by the RFF Silent Install Switch Finder (getrff.com) - review before deploying.

.DESCRIPTION
    The CONFIGURED deploy script - NOT the engine. It needs the PSAppDeployToolkit v4 module present
    (a sibling .\\PSAppDeployToolkit folder, or installed: Save-Module PSAppDeployToolkit). Get the
    template from https://psappdeploytoolkit.com, drop this file + your installer (into .\\Files), then:
        .\\Invoke-AppDeployToolkit.ps1 -DeploymentType Install -DeployMode Silent
    (or run Invoke-AppDeployToolkit.exe). No framework? Use the .intunewin from the tool - it wraps the
    installer directly and needs none of this.

    NOTE: On Windows PowerShell 5.1, importing PSADT v4 can throw a type-data error
    ("The member ... is already present"). That is a known PSADT/PS 5.1 quirk, not a script bug.
    If you hit it, run this with PowerShell 7 instead:  pwsh -File .\\Invoke-AppDeployToolkit.ps1 ...
    (or just use Invoke-AppDeployToolkit.exe, which targets the right runtime).
#>
[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    # Changes to user-install mode and back, for installing/uninstalling on RDS Host / Citrix servers.
    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode
)

## MARK: Variables
$adtSession = @{
    AppVendor = '${ps(i.vendor)}'
    AppName = '${ps(nm)}'
    AppVersion = '${ps(i.version)}'
    AppArch = ''
    AppLang = 'EN'
    AppRevision = '01'
    AppSuccessExitCodes = @(0)
    AppRebootExitCodes = @(1641, 3010)
    AppProcessesToClose = @()

    AppScriptVersion = '1.0.0'
    AppScriptDate = '${date}'
    AppScriptAuthor = 'RFF Silent Install Switch Finder'

    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters = $PSBoundParameters
    DeployAppScriptVersion = '4.0.0'
}

## MARK: Pre-Install
\${Pre-Install} = {
    Show-ADTInstallationProgress
}

## MARK: Install
\${Install} = {
${actionLines(i, 'Install')}
}

## MARK: Post-Install
\${Post-Install} = {
}

## MARK: Pre-Uninstall
\${Pre-Uninstall} = {
    Show-ADTInstallationProgress
}

## MARK: Uninstall
\${Uninstall} = {
${actionLines(i, 'Uninstall')}
}

## MARK: Post-Uninstall
\${Post-Uninstall} = {
}

## MARK: Pre-Repair
\${Pre-Repair} = {
    Show-ADTInstallationProgress
}

## MARK: Repair
\${Repair} = {
${actionLines(i, 'Install')}
}

## MARK: Post-Repair
\${Post-Repair} = {
}

## MARK: Initialization
$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1
try
{
    if (Test-Path -LiteralPath "$PSScriptRoot\\PSAppDeployToolkit\\PSAppDeployToolkit.psd1" -PathType Leaf)
    {
        Get-ChildItem -LiteralPath "$PSScriptRoot\\PSAppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\\PSAppDeployToolkit\\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.0.0' } -Force
    }
    else
    {
        Import-Module -FullyQualifiedName @{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.0.0' } -Force
    }
    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
    Remove-Variable -Name iadtParams -Force -Confirm:$false
}
catch
{
    if ("$_" -match 'is already present|FormatXmlUpdateException|TypeData')
    {
        $Host.UI.WriteErrorLine('PSAppDeployToolkit IS installed, but it failed to import under Windows PowerShell 5.1 with a type-data clash ("The member ... is already present"). This is a known PSADT v4 / PS 5.1 quirk, NOT a problem with this script. Re-run it with PowerShell 7:  pwsh -File "' + $MyInvocation.MyCommand.Path + '" -DeploymentType Install -DeployMode Silent  (or use Invoke-AppDeployToolkit.exe).')
    }
    else
    {
        $Host.UI.WriteErrorLine('PSAppDeployToolkit v4 (4.0.0 or newer) is required but was not found. This .ps1 is only the deploy script - PSADT is the engine. Either run it from inside a PSADT v4 template folder that bundles the module (drop this file + your installer into .\\Files), or install the module:  Install-Module PSAppDeployToolkit -Scope CurrentUser -Force  (run [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12 first if PSGallery fails). If you do not actually need PSADT, the RFF tool also gives you a .intunewin and a raw silent command that need NO framework at all.')
    }
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int16]::MaxValue)))
    exit 60008
}

## MARK: Invocation
try
{
    Get-Variable -Name "Pre-$($adtSession.DeploymentType)", $adtSession.DeploymentType, "Post-$($adtSession.DeploymentType)" -ErrorAction Ignore | . {
        process
        {
            if (![System.String]::IsNullOrWhiteSpace($_.Value))
            {
                $adtSession.InstallPhase = $_.Name
                . $_.Value
            }
        }
    }
    Close-ADTSession
}
catch
{
    Write-ADTLogEntry -Message "An unhandled error within [$($MyInvocation.MyCommand.Name)] has occurred: $(Resolve-ADTErrorRecord -ErrorRecord $_)" -Severity Error
    Close-ADTSession -ExitCode 60001
}
`;
}

export type DeployMode = 'Silent' | 'Interactive' | 'NonInteractive' | 'Auto';
export type DetectionKind = 'msi' | 'file' | 'registry';

/** The commonly-needed PSADT knobs that change the .exe invocation (not the .ps1 body). */
export interface PsadtOptions {
  deployMode: DeployMode;
  /** Add -SuppressRebootPassThru so a 3010 (reboot required) is reported to the deploy tool as success. */
  suppressReboot: boolean;
  /** Add -TerminalServerMode to wrap install in RDS/Citrix change-user mode. */
  terminalServerMode: boolean;
}

/** Build the Invoke-AppDeployToolkit.exe install/uninstall commands for the chosen options. */
export function psadtCommands(o: PsadtOptions): { install: string; uninstall: string } {
  const tail =
    (o.deployMode && o.deployMode !== 'Auto' ? ` -DeployMode ${o.deployMode}` : '') +
    (o.suppressReboot ? ' -SuppressRebootPassThru' : '') +
    (o.terminalServerMode ? ' -TerminalServerMode' : '');
  return {
    install: `Invoke-AppDeployToolkit.exe -DeploymentType Install${tail}`,
    uninstall: `Invoke-AppDeployToolkit.exe -DeploymentType Uninstall${tail}`,
  };
}

/** Best default detection rule: MSI product code if we have one, otherwise a registry rule. */
export function defaultDetectionKind(i: PsadtInput): DetectionKind {
  return i.msiProductCode ? 'msi' : 'registry';
}

/** A copy-pasteable Intune detection-rule description for the chosen rule type. */
export function detectionRule(i: PsadtInput, kind: DetectionKind): string {
  if (kind === 'msi') {
    return i.msiProductCode
      ? `MSI product code: ${i.msiProductCode}`
      : 'No MSI product code was detected for this installer - use a File or Registry rule instead.';
  }
  if (kind === 'file') {
    // EXE installers (NSIS/Inno/etc.) don't record their target path in the file - it's chosen at
    // install time - so this is a SHAPE to fill in, never derived from the dropped installer. (We
    // deliberately don't splice the installer's filename into the path; that produced garbage.)
    const vendor = i.vendor && i.vendor.length <= 40 ? i.vendor : '<Vendor>';
    return `File exists: point this at a file the app installs, e.g. "C:\\Program Files\\${vendor}\\<App>\\<app>.exe". The installer doesn't carry its install path, so set this to a real file you know it drops (check "Program Files (x86)" for 32-bit apps).`;
  }
  const key = i.msiProductCode || '<ProductCode-or-AppKey>';
  return `Registry: HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${key} -> "DisplayVersion" = "${i.version || '<version>'}"  (use ...\\WOW6432Node\\... for 32-bit installs on 64-bit Windows).`;
}
